my_works = {
    "🧺 Корзины": [
        {"title": "Корзина", "callback": "work_basket_1", "photo": "media/works/basket/basket.jpg"},
        {"title": "Корзина 1", "callback": "work_basket_2", "photo": "media/works/basket/basket1.jpg"},
        {"title": "Корзина 2", "callback": "work_basket_3", "photo": "media/works/basket/basket2.jpg"},
        {"title": "Корзина 3", "callback": "work_basket_4", "photo": "media/works/basket/basket3.jpg"},
        {"title": "Корзина 4", "callback": "work_basket_5", "photo": "media/works/basket/basket4.jpg"},
    ],
    "🧸 Мишки-Тедди": [
        {"title": "Медведь", "callback": "work_bear_1", "photo": "media/works/bear/bear.jpg"},
        {"title": "Медведь 1", "callback": "work_bear_2", "photo": "media/works/bear/bear1.jpg"},
        {"title": "Медведь 2", "callback": "work_bear_3", "photo": "media/works/bear/bear2.jpg"},
        {"title": "Медведь 3", "callback": "work_bear_4", "photo": "media/works/bear/bear3.jpg"},
    ],
    "🚪 Миниатюра на полку": [
        {"title": "Шкаф", "callback": "work_closet_1", "photo": "media/works/closet/closet.jpg"},
        {"title": "Шкаф 2", "callback": "work_closet_2", "photo": "media/works/closet/closet2.jpg"},
        {"title": "Шкаф 3", "callback": "work_closet_3", "photo": "media/works/closet/closet3.jpg"},
        {"title": "Шкаф 4", "callback": "work_closet_4", "photo": "media/works/closet/closet4.jpg"},
        {"title": "Шкаф 5", "callback": "work_closet_5", "photo": "media/works/closet/closet5.jpg"},
        {"title": "Шкаф 6", "callback": "work_closet_6", "photo": "media/works/closet/closet6.jpg"},
        {"title": "Шкаф 7", "callback": "work_closet_7", "photo": "media/works/closet/closet7.jpg"},
    ],
    # "🧸 Куклы": [
    #     {"title": "Кукла", "callback": "work_doll_1", "photo": "media/works/doll/doll.jpg"},
    #     {"title": "Кукла 1", "callback": "work_doll_2", "photo": "media/works/doll/doll1.jpg"},
    # ],
    "🪑 Мебель": [
        {"title": "Мебель", "callback": "work_furniture_1", "photo": "media/works/furniture/furniture.jpg"},
        {"title": "Мебель 1", "callback": "work_furniture_2", "photo": "media/works/furniture/furniture1.jpg"},
        {"title": "Мебель 2", "callback": "work_furniture_3", "photo": "media/works/furniture/furniture2.JPG"},
        {"title": "Мебель 3", "callback": "work_furniture_4", "photo": "media/works/furniture/furniture3.JPG"},
        {"title": "Мебель 4", "callback": "work_furniture_5", "photo": "media/works/furniture/furniture4.jpg"},
        {"title": "Мебель 5", "callback": "work_furniture_6", "photo": "media/works/furniture/furniture5.jpg"},
    ],
    "🏡 Миниатюры": [
        {"title": "Миниатюра", "callback": "work_miniature_1", "photo": "media/works/miniature/miniature.jpg"},
        {"title": "Миниатюра 1", "callback": "work_miniature_2", "photo": "media/works/miniature/miniature1.jpg"},
        {"title": "Миниатюра 2", "callback": "work_miniature_3", "photo": "media/works/miniature/miniature2.jpg"},
        {"title": "Миниатюра 3", "callback": "work_miniature_4", "photo": "media/works/miniature/miniature3.JPG"},
        {"title": "Миниатюра 4", "callback": "work_miniature_5", "photo": "media/works/miniature/miniature4.jpg"},
        {"title": "Миниатюра 5", "callback": "work_miniature_6", "photo": "media/works/miniature/miniature5.JPG"},
        {"title": "Миниатюра 6", "callback": "work_miniature_7", "photo": "media/works/miniature/miniature6.jpg"},
        {"title": "Миниатюра 7", "callback": "work_miniature_8", "photo": "media/works/miniature/miniature7.jpg"},
        {"title": "Миниатюра 8", "callback": "work_miniature_9", "photo": "media/works/miniature/miniature8.jpg"},
    ],
    "🎄 Новогодние": [
        {"title": "Новогоднее", "callback": "work_newyear_1", "photo": "media/works/newyear/newyear.jpg"},
        {"title": "Новогоднее 1", "callback": "work_newyear_2", "photo": "media/works/newyear/newyear1.jpg"},
        {"title": "Новогоднее 2", "callback": "work_newyear_3", "photo": "media/works/newyear/newyear2.jpg"},
        {"title": "Новогоднее 3", "callback": "work_newyear_4", "photo": "media/works/newyear/newyear3.jpg"},
    ],
    "🛋️ Рум-бокс": [
        {"title": "Ящик", "callback": "work_roombox_1", "photo": "media/works/roombox/roombox.jpg"},
        {"title": "Ящик 1", "callback": "work_roombox_2", "photo": "media/works/roombox/roombox1.jpg"},
        {"title": "Ящик 2", "callback": "work_roombox_3", "photo": "media/works/roombox/roombox2.jpg"},
        {"title": "Ящик 3", "callback": "work_roombox_4", "photo": "media/works/roombox/roombox3.jpg"},
    ],
    "🌊 Море": [
        {"title": "Море", "callback": "work_sea_1", "photo": "media/works/sea/sea.jpg"},
        {"title": "Море 2", "callback": "work_sea_2", "photo": "media/works/sea/sea2.jpg"},
    ],
    "❄️ Снеговики": [
        {"title": "Снеговик", "callback": "work_snowman_1", "photo": "media/works/snowman/snowman.jpg"},
        {"title": "Снеговик 1", "callback": "work_snowman_2", "photo": "media/works/snowman/snowman1.jpg"},
        {"title": "Снеговик 2", "callback": "work_snowman_3", "photo": "media/works/snowman/snowman2.JPG"},
        {"title": "Снеговик 3", "callback": "work_snowman_4", "photo": "media/works/snowman/snowman3.jpg"},
        {"title": "Снеговик 4", "callback": "work_snowman_5", "photo": "media/works/snowman/snowman4.jpg"},
    ],
}